// `shoshin evening` — reconvene flow. Summarizes day's activity, presents
// a MEMORY.md candidate entry built from advanced tickets + trail tail,
// and (optionally) appends after user approval.
//
// Foundation phase: deterministic summary template. Future: dispatch
// Librarian (Borges + Knuth) to compose the entry, with the user
// approving the librarian's draft.
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import kleur from "kleur";
import readline from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { readTickets } from "./tickets.js";
import { readFeatures } from "../features/store.js";
import { readTrailTail } from "../trail/reader.js";
import { Trail } from "../trail/writer.js";
import { projectRoot } from "../util/paths.js";

export interface EveningOptions {
  noPrompt?: boolean; // skip interactive append confirmation; just print the candidate
}

export async function runEvening(opts: EveningOptions = {}): Promise<void> {
  const cwd = projectRoot();
  const tickets = readTickets(cwd);
  const features = readFeatures(cwd);
  const trail = readTrailTail(50, cwd);

  const completed = tickets.tickets.filter((t) => t.status === "completed");
  const blocked = tickets.tickets.filter((t) => t.status === "blocked");

  const advancedCount = features.features.reduce(
    (acc, f) => acc + f.history.filter((h) => h.at >= tickets.date).length,
    0,
  );

  console.log(kleur.bold(kleur.magenta("\n🌙 Evening reconvene\n")));
  console.log(`  date:               ${tickets.date}`);
  console.log(`  tickets completed:  ${completed.length}`);
  console.log(`  tickets blocked:    ${blocked.length}`);
  console.log(`  features advanced:  ${advancedCount}`);
  console.log(`  trail records:      ${trail.length}\n`);

  // Build a MEMORY.md candidate entry.
  const candidate = buildMemoryCandidate({
    date: tickets.date,
    completed: completed.length,
    blocked: blocked.length,
    advancedCount,
    sampleAdvances: features.features
      .flatMap((f) => f.history.filter((h) => h.at >= tickets.date).map((h) => ({ id: f.id, h })))
      .slice(0, 5),
  });

  console.log(kleur.bold("Candidate MEMORY.md entry:\n"));
  console.log(kleur.gray("─".repeat(60)));
  console.log(candidate);
  console.log(kleur.gray("─".repeat(60)));

  Trail.evening(advancedCount, blocked.length);

  if (opts.noPrompt) {
    console.log(kleur.gray("\n  (--no-prompt) candidate not appended; copy manually if desired."));
    return;
  }

  const memoryPath = join(cwd, "MEMORY.md");
  const exists = existsSync(memoryPath);

  const rl = readline.createInterface({ input: stdin, output: stdout });
  const ans = (await rl.question(
    kleur.bold(`\nAppend to ${exists ? "MEMORY.md" : "MEMORY.md (new file)"}? [y/N] `),
  )).trim().toLowerCase();
  rl.close();

  if (ans === "y" || ans === "yes") {
    const prefix = exists ? "\n\n" : "# Project Memory\n\n";
    appendFileSync(memoryPath, prefix + candidate + "\n", "utf8");
    console.log(kleur.green(`✓ Appended to ${memoryPath}`));
    Trail.spawn("librarian", "evening compaction", ["MemoryWriteCap"]);
  } else {
    console.log(kleur.gray("Skipped — candidate above is yours to do whatever with."));
  }
}

interface MemoryCandidateInput {
  date: string;
  completed: number;
  blocked: number;
  advancedCount: number;
  sampleAdvances: Array<{ id: string; h: { from: string; to: string; evidence?: string } }>;
}

function buildMemoryCandidate(d: MemoryCandidateInput): string {
  const lines: string[] = [];
  lines.push(`## ${d.date} — Daily Reconvene`);
  lines.push("");
  lines.push(`- Tickets completed: ${d.completed}`);
  lines.push(`- Tickets blocked: ${d.blocked}`);
  lines.push(`- Feature advances: ${d.advancedCount}`);
  if (d.sampleAdvances.length > 0) {
    lines.push("");
    lines.push("**Sample advances:**");
    for (const a of d.sampleAdvances) {
      const ev = a.h.evidence ? ` — _${a.h.evidence.slice(0, 80)}_` : "";
      lines.push(`- \`${a.id}\`: ${a.h.from} → ${a.h.to}${ev}`);
    }
  }
  lines.push("");
  lines.push("_Generated by `shoshin evening` (Librarian compaction stub)._");
  return lines.join("\n");
}
