// Tickets generated by `shoshin morning` and consumed by `shoshin run`.
// Each ticket is a single-role dispatch the orchestrator can execute
// without further human input.
//
// Tickets sit in .shoshin/tickets.json between morning and run; the
// evening flow archives completed tickets into the trail.
import { z } from "zod";
import { ROLE_NAMES } from "../roles/types.js";
import { FEATURE_STATES } from "../features/types.js";
import { readJsonOr, writeJson } from "../util/json-io.js";
import { shoshinFile, shoshinDir } from "../util/paths.js";
import { join } from "node:path";

export const TICKET_STATUSES = ["queued", "in_flight", "completed", "blocked"] as const;
export type TicketStatus = (typeof TICKET_STATUSES)[number];

export const TicketSchema = z.object({
  id: z.string().min(1),
  role: z.enum(ROLE_NAMES),
  feature: z.string().min(1),
  brief: z.string().min(1),
  proposedAdvance: z.enum(FEATURE_STATES).optional(),
  status: z.enum(TICKET_STATUSES).default("queued"),
  createdAt: z.string(),
  startedAt: z.string().optional(),
  completedAt: z.string().optional(),
  durationMs: z.number().optional(),
  outputDigest: z.string().optional(),
});
export type Ticket = z.infer<typeof TicketSchema>;

export const TicketsFileSchema = z.object({
  version: z.literal(1).default(1),
  date: z.string(),
  tickets: z.array(TicketSchema).default([]),
});
export type TicketsFile = z.infer<typeof TicketsFileSchema>;

const EMPTY: TicketsFile = { version: 1, date: "", tickets: [] };

function ticketsPath(cwd?: string): string {
  return join(shoshinDir(cwd), "tickets.json");
}

export function readTickets(cwd?: string): TicketsFile {
  const raw = readJsonOr<unknown>(ticketsPath(cwd), EMPTY);
  const parsed = TicketsFileSchema.safeParse(raw);
  if (!parsed.success) {
    throw new Error(`Invalid .shoshin/tickets.json: ${parsed.error.message}`);
  }
  return parsed.data;
}

export function writeTickets(file: TicketsFile, cwd?: string): void {
  const validated = TicketsFileSchema.parse(file);
  writeJson(ticketsPath(cwd), validated);
}

export function newTicketId(): string {
  return `t_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

export function newTicket(input: Omit<Ticket, "id" | "createdAt" | "status">): Ticket {
  return {
    id: newTicketId(),
    createdAt: new Date().toISOString(),
    status: "queued",
    ...input,
  };
}
